#!/bin/bash
cd /home/admin/MCSTrack
source .venv/bin/activate
export MCSTRACK_DETECTOR_CONFIGURATION_FILEPATH="/home/admin/MCSTrack/data/configuration/detector/rpicam_aruco.json"
python -m src.main_detector
