import cv2
from typing import Final, Literal

CornerRefinementMethod = Literal["NONE", "SUBPIX", "CONTOUR", "APRILTAG"]
CORNER_REFINEMENT_METHOD_NONE: Final[str] = 'NONE'
CORNER_REFINEMENT_METHOD_SUBPIX: Final[str] = 'SUBPIX'
CORNER_REFINEMENT_METHOD_CONTOUR: Final[str] = 'CONTOUR'
CORNER_REFINEMENT_METHOD_APRILTAG: Final[str] = 'APRILTAG'

CORNER_REFINEMENT_METHOD_DICTIONARY_TEXT_TO_INT: dict[CornerRefinementMethod, int] = {
    "NONE": cv2.aruco.CORNER_REFINE_NONE,
    "SUBPIX": cv2.aruco.CORNER_REFINE_SUBPIX,
    "CONTOUR": cv2.aruco.CORNER_REFINE_CONTOUR,
    "APRILTAG": cv2.aruco.CORNER_REFINE_APRILTAG}

CORNER_REFINEMENT_METHOD_DICTIONARY_INT_TO_TEXT: dict[int, CornerRefinementMethod] = {
    cv2.aruco.CORNER_REFINE_NONE: "NONE",
    cv2.aruco.CORNER_REFINE_SUBPIX: "SUBPIX",
    cv2.aruco.CORNER_REFINE_CONTOUR: "CONTOUR",
    cv2.aruco.CORNER_REFINE_APRILTAG: "APRILTAG"}
